// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yebpdjnlbjfrpaunryah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllYnBkam5sYmpmcnBhdW5yeWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjc3MzYsImV4cCI6MjA3MTc0MzczNn0.QW368wcuNst1cnOk0K9jF-WPfcNbZtle29XqMcwp0do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});